rules:
  # SQL Injection Detection
  - id: sql-injection-fstring
    patterns:
      - pattern: execute(f"...")
      - pattern-not: execute(text(...), ...)
    message: "Potential SQL injection using f-string"
    languages: [python]
    severity: ERROR
    
  - id: sql-injection-concat
    pattern: execute("..." + $VAR + "...")
    message: "Potential SQL injection using string concatenation"
    languages: [python]
    severity: ERROR

  # Hardcoded Secrets
  - id: hardcoded-password
    patterns:
      - pattern-either:
          - pattern: password = "..."
          - pattern: api_key = "..."
          - pattern: secret = "..."
          - pattern: token = "..."
    message: "Hardcoded secret detected"
    languages: [python]
    severity: WARNING

  # Missing Error Handling
  - id: unhandled-db-operation
    patterns:
      - pattern: |
          async def $FUNC(...):
            ...
            $DB.execute(...)
      - pattern-not-inside: |
          try:
            ...
          except:
            ...
    message: "Database operation without error handling"
    languages: [python]
    severity: WARNING

  # CORS Misconfiguration
  - id: cors-allow-all
    pattern: |
      CORSMiddleware(..., allow_origins=["*"], ...)
    message: "CORS configured to allow all origins"
    languages: [python]
    severity: WARNING
